### ISSUE TITLE
improve performance

### ISSUE THREAD

**Issue by Akida31** [cryptic-game/website#120]
### Problems
- large images (especially blog_post.png = 2MB) -> most of the data
- page loading wrong without JS enabled, discord logo is too big, see image below
![screenshot](https://user-images.githubusercontent.com/47895118/106323113-2c5f3780-6277-11eb-9c35-d2dd1c6dea7c.png)

**Comment by JannikEmmerich** [comment]
@dependabot recreate

**Comment by 1Spinne** [comment]
also with javascript enabled

**Comment by ClientCrash** [comment]
We could load the logo AFTER the website is already there.  This would prevent the bug. I will also look at the code and look if i can find the issue.

**Comment by ClientCrash** [comment]
@MarcelCoding this can be closed. The Discord button issue has been fixed and the images isnt something that can be fixed in the code, also theres lazyload for blogpost images.

**Comment by Akida31** [comment]
thank you!
