### ISSUE TITLE
Video doesn´t plays always

### ISSUE THREAD

**Issue by 1Spinne** [cryptic-game/website#229]
The video will not play if you click on a link that does not open a new tab and then go back to home page

**Comment by ClientCrash** [comment]
It works for me (Chrome, Win10). The bug is only there for Firefox. Can we even fix this or is this some sort of Pop-Up protection or something from the browser?

**Comment by 1Spinne** [comment]
ich sags auf Deutsch: Ich habe den PopUpBlocker nicht an

**Comment by 1Spinne** [comment]
Es gibt auch keine Einstellung für Autoplay und es funktioniert ja, wenn man das erste mal drauf kommt oder man die Seite neulädt

**Comment by ClientCrash** [comment]
Ja ich denke Firefox lässt nur eine begrenzte Anzahl an Autoplays pro Webseite zu. Ich kann später aber nochmal drüber gucken.

**Comment by ClientCrash** [comment]
> As a general rule, you can assume that media will be allowed to autoplay only if at least one of the following is true:
The audio is muted or its volume is set to 0
**The user has interacted with the site** (by clicking, tapping, pressing keys, etc.) [...] 
~ Mozilla (https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide)
