### ISSUE TITLE
The 404 page doesn‘t work

### ISSUE THREAD

**Issue by 1Spinne** [cryptic-game/website#245]
iPhone:
![50EB8731-B2E4-44C2-A053-A244044A8838](https://user-images.githubusercontent.com/66938161/131215936-d17421be-a9fb-4ce4-b8f6-2c224a32f333.png)
Computer (RasPI 400):
![D445D3E0-63E8-4D3A-A175-4360CB6ABA84](https://user-images.githubusercontent.com/66938161/131216039-675e1343-f2fa-45d3-864c-0111a34ee11c.jpeg)

**Comment by ClientCrash** [comment]
Text is displayed in my browser for half a second, then the rest of the page loads and the text disappears. The side is then black.

**Comment by ClientCrash** [comment]
Is this still relevant @1Spinne  . Pls test again.

**Comment by ClientCrash** [comment]
Works on localhost but not on server.

**Comment by ClientCrash** [comment]
The issue seems to be a problem with the server (/cloudflare pages?) not with nuxt. Please look into it @MarcelCoding .

**Comment by MarcelCoding** [comment]
@ClientCrash I could find the problem. But I was able to verify that the problem isn't occurring if you use the npm package `serve` (simple static HTTP server).

**Comment by ClientCrash** [comment]
> @ClientCrash I couldn't find the problem. But I was able to verify that the problem isn't occurring if you use the npm package `serve` (simple static HTTP server).

Yes. It seems to be a problem with CF Pages.
