### ISSUE TITLE
Footer has margin bottom.

### ISSUE THREAD

**Issue by ClientCrash** [cryptic-game/website#252]
**Describe the bug**
The footer has a margin on the bottom

![tempsnip](https://user-images.githubusercontent.com/40364569/132394206-5a01d08c-477c-46dc-9534-d3b68af2ad6d.png)

**Comment by JannikEmmerich** [comment]
Please add how to reproduce this bug.

**Comment by ClientCrash** [comment]
@JannikEmmerich sorry the issue contained false infromation, please look at the updated issue. There was a misunderstanding.
