### ISSUE TITLE
Blog articles are misplaced [UI-Bug]

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/website#301]
**Describe the bug**
Auf der Startseite sind die Blogartikel verschoben. Sind nicht in der gleichen flucht wie andere Textelememente.

![grafik](https://user-images.githubusercontent.com/44207756/138553900-5a0f0909-b053-42b5-9495-332b45d4b661.png)

**Additional Comments**
Gestest auf dem Desktop im Browser.
Firefox v93.0

**Comment by ClientCrash** [comment]
The blog articles have this width because the mobile and tablet ui improvements required this change. I can look into a method of setting different css rules for the index page blog cards but this isnt a very clean method. Maybe i will work on it later. I will think about it for now.

**Comment by DevMimas** [comment]
Before, yes it was right after we implemented the new blog backend. I think that's definitely implementable and it just doesn't look nice like this.

**Comment by ClientCrash** [comment]
- [ ] Use old css rules if blog cards are on index page.
