### ISSUE TITLE
Dockerfile for Database

### ISSUE THREAD

**Issue by RiseofRice** [cryptic-game/website#33]
## Description
- [ ] Database = MongoDB
- [ ] specify volume for the data 
- [ ] expose ports

**Comment by use-to** [comment]
You should not add Dockerfiles like that. The database will be added to our [docker-compose.yml](https://github.com/cryptic-game/cryptic/blob/master/docker-compose.prod.yml).

**Comment by use-to** [comment]
Switching to mariadb or mysql.
