### ISSUE TITLE
Optimizing SEO - Very important!

### ISSUE THREAD

**Issue by Webkinger** [cryptic-game/website#344]
Optimize the website SEO so that you can e.g. can also be found better in Google, Bing and so on

### Things that need to be adjusted
- Keywords are completely missing. 
- In many blog posts it doesn't have a description or says author.
- Important meta tags for the search engine are missing.

### Infromation about SEO
- [https://developers.google.com/search/docs/beginner/seo-starter-guide](https://developers.google.com/search/docs/beginner/seo-starter-guide)
- [https://www.semrush.com/blog/seo-tips/](https://www.semrush.com/blog/seo-tips/)

### Tools
- [https://de.semrush.com/analytics/keywordmagic/start](https://de.semrush.com/analytics/keywordmagic/start)
- [https://www.keywordtooldominator.com/](https://www.keywordtooldominator.com/)
- [https://www.ionos.de/digitalguide/websites/web-entwicklung/die-wichtigsten-meta-tags-im-ueberblick/](https://www.ionos.de/digitalguide/websites/web-entwicklung/die-wichtigsten-meta-tags-im-ueberblick/)

**Comment by ClientCrash** [comment]
https://discord.com/channels/454739001841025024/533334373026627585/946898006446313542 @MarcelCoding @DevMimas

**Comment by ClientCrash** [comment]
- [ ] Add author tag
- [ ] Add date tag
- [ ] Add description tag

**Comment by MarcelCoding** [comment]
If we don't need to block content from being indexed, do we need a robots.txt?

**Comment by ClientCrash** [comment]
I agree with Marcel, i dont think we need a robots.txt. @EggerWebdesign
