### ISSUE TITLE
Typewriter effect

### ISSUE THREAD

**Issue by ClientCrash** [cryptic-game/website#75]
## Description
A typewriter effect that cycles through all of our subtitles.

## Additional context

Als Text gemeint war der 2. Teil des Cryptic Slogans also alles was nach dem "Cryptic - " kommt also zB "The hacker Game". Auf der Webseite könnte das Element zB. als Ersatz für "Dont play the game , create the game" fungieren muss es aber nicht. Ich könnte mir auch eine Platzierung in der Mitte links gut vorstellen also über der freien fläche des Videos.  Es würde sich auch anbieten das bestimmte jetzt schon existierende Schriftzüge nicht sofort da sind sonder erst nach etwa einer halben Sekunde mit dem Effekt erscheinen. So könnte mann zB die Seite laden und nach ein paar sekunden erscheint zB der Schriftzug "dont play the game create the game" oder "Join us today", meiner Meinung nach ist das eine gute idee und ich denke das dieser Style gut zu einem Hacker Game passt.

Link to: [concept](https://imgur.com/a/lLzpCj7)

**Comment by Paul-Kl01** [comment]
Ich würde die Issue bearbeiten. Es muss mir nur jemand sagen, welcher Text gemeint ist. 
Meint ihr den Slogan? @DevMimas
