### ISSUE TITLE
Update roadmap pre alpha 3

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/website#78]
## Description

Update the roadmap page from pre-alpha 3

If you have any questions please ask me @DevMimas

**Comment by ULUdev** [comment]
Hey, I want to work on this issue. Could someone add me as a contributor, so that I can push to a branch made for this issue?

**Comment by JannikEmmerich** [comment]
Hi @ULUdev,
please fork our repository and create the branch for this issue within your fork. When you're finished, you can create a pull request to our repository.
