### ISSUE TITLE
Multilingual mode

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/website#80]
## Description

On the website, it should be possible to switch between several languages. All visible texts should be translated into the respective language, including blog texts.

The first languages are German and English. Other languages are not excluded. We'll see.

## Problem
Currently only one language available. This means that you are addressing fewer readers.

## Additional context
The blog texts are managed via a separately hosted platform "Ghost". Here it must be checked whether and how these blog texts can be implemented in several languages.

**Links:**
[wie-du-einen-mehrsprachigen-ghost-blog-mit-docker-und-nginx-aufsetzt](https://steampixel.de/wie-du-einen-mehrsprachigen-ghost-blog-mit-docker-und-nginx-aufsetzt/)

[ghost.org/tutorials/multi-language-content](https://ghost.org/tutorials/multi-language-content/)

**Comment by ULUdev** [comment]
<p>I have two ideas</p>
<ul>
<li>seperate versions of the files (in the url: https://cryptic-game.net/de/roadmap)</li>
<li>dynamic pages (in the url: https://cryptic-game.net/roadmap?lang=de)</li>
</ul>
<p>the first one is probably easier to make but also much more inefficient<br>
I could attempt the first one</p>

**Comment by Akida31** [comment]
@DevMimas assign?
