### ISSUE TITLE
Add a changelog page

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/website#86]
**Is your feature request related to a problem? Please describe.**
We don`t have a changelog page

**Describe the solution you'd like**
Add a changelog page and use the changelog.json file from the game

**Comment by 1Spinne** [comment]
Roadmap is the Changelog page, isnßt it?

**Comment by ClientCrash** [comment]
no. The changelog page shows bugs that where patched and features added. The roadmap is only a broad plan of the future. Bugfixes as well as small changes are often not included in the roadmap. I have already programmed the changelog page and im just waiting for it to get merged.
