### ISSUE TITLE
Update team page

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/website#87]
**Describe the solution you'd like**
Update the team page on the website

If you have any questions please ask me @DevMimas

**Comment by Paul-Kl01** [comment]
**Ansatz zur Nutzung der API für die Teamseite:**

- [ ] install axios and vue-axios
- [ ] Component erstellen
- [ ] Api fetch mit axios
- [ ] Data view hinzufügen (v-for nutzen)

[https://www.youtube.com/watch?v=Kbm9HsF_7-4](url)

**Comment by MarcelCoding** [comment]
This has to be implemented https://github.com/cryptic-game/website/issues/87#issuecomment-708545893
@JannikEmmerich

**Comment by JannikEmmerich** [comment]
This is not mentioned in the initial issue and we should create a new issue with more instructions for the developers for it.
