### ISSUE TITLE
Website icon incorrect display on YouTube

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/website#93]
**Describe the bug**
Das Icon wird auf YouTube in der Kanalinfo mit einem weißem Hintergrund angezeigt.

![grafik](https://user-images.githubusercontent.com/44207756/95013215-29449980-063f-11eb-9ee1-95aeb95bbffb.png)

**Additional Comments**
Mal der Sache auf den Grund gehen, wieso das in YT falsch angezeigt wird. Im Browsertab der Website ist das nicht der Fall.
Anzeigefehler in Firefox v81

**Comment by ClientCrash** [comment]
# Fehler tritt nicht länger auf.   
Weder auf Firefox noch auf Chrome. Woran auch immer das lag, der Bug ist mit neueren Versionen nicht reproduzierbar. @DevMimas
